version: "3.7"

services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    #env_file: .env
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Jakarta
      - PASSWORD=Mohammed21!
      - SUDO_PASSWORD=Mohammed21!
    volumes:
      - ./config:/config
    ports:
      - 8433:8443
  openvscode-server:
    image: gitpod/openvscode-server
    container_name: openvscode-server
    volumes:
      - workspace:/home/workspace:cached
    ports:
      - 3010:3000
  server:
    image: codercom/code-server:latest
    container_name: server
    volumes:
      - project:/home/coder/project
    ports:
      - 8088:8080

volumes:
  workspace:
  project:
